app_id: 123578884349165
api_key: cfa53e39517884b6bde5cb24a62e5404
secret: 5404dfe2d08cda6abbb65f65ef695d3c
fb_url: http://apps.facebook.com/mykaribu
direct_url: http://mykaribu2.appspot.com
gs_api_key: ABQIAAAAxrWTmduFuxVU4bQUPiSLjxTMLxEwOSeuNGVTMiiVDNogrz0ichQOFuxyy3CFtZKtqr70wilfaq_kZA